include:
  - ./compose_include/config1.yaml

services:
  microros-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: developer
        USER_UID: 2000
        USER_GID: 2000
    container_name: microros-platformio-jazzy
    volumes:
      # Mount your PlatformIO project directory (This should bind mount to)
      # - .:/workspace
      - workspace:/workspace
      # Persist PlatformIO packages and toolchains
      - platformio-packages:/home/developer/.platformio
      # Mount USB devices for flashing
      - /dev:/dev
    privileged: true  # Needed for USB device access
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}  # For GUI tools if needed
      - ROS_DOMAIN_ID=42   # Set ROS domain ID
    network_mode: host  # For ROS2 communication
    working_dir: /home/developer
## It does mount
volumes:
  platformio-packages: