services:
  microros-dev:
    build:
      # Can change build context with cmd to other stuffs
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: developer
        USER_UID: 2000
        USER_GID: 2000
    container_name: bp-ros-cont2
    volumes:
      # Only stores containers dependencies and toolchains within container
      - platformio-packages:/home/developer/.platformio
      # - rosbuild-cache:/home/developer/microros_ws
      # - piobuild-cache:/home/developer/pio_projects
      # Mount All USB devices from /dev path
      - /dev:/dev
      # # Mount your PlatformIO project directory
      - ./pio_projects:/home/developer/pio_projects
      - ./microros_ws/src/my_pkgs:/home/developer/microros_ws/src/my_pkgs
    privileged: true  # Needed for USB device access
    stdin_open: true  # -i equivalent std input is open for terminal , what about std_output
    tty: true         # -t equivalent
    environment:
      - DISPLAY=${DISPLAY}  # For GUI tools if needed
      - ROS_DOMAIN_ID=42   # Set ROS domain ID
    network_mode: host  # For ROS2 communication
    working_dir: /home/developer
## It does mount
volumes:
  platformio-packages:
  # rosbuild-cache:
  # piobuild-cache: