# include:
#   - ./compose_include/config1.yaml

services:
  microros-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: developer
        USER_UID: 2000
        USER_GID: 2000
    container_name: bp-ros-cont
    volumes:
      # Mount your PlatformIO project directory (This should bind mount to)
      - ./projects:/home/developer/pio_projects
      # Stores PIO packages and toolchains in volume
      - platformio-packages:/home/developer/.platformio
      # Mount USB devices for flashing (This will mount from Linux system)
      - /dev:/dev
    privileged: true  # Needed for USB device access
    stdin_open: true  # -i equivalent std input is open for terminal , what about std_output
    tty: true         # -t equivalent
    environment:
      - DISPLAY=${DISPLAY}  # For GUI tools if needed
      - ROS_DOMAIN_ID=42   # Set ROS domain ID
    network_mode: host  # For ROS2 communication
    working_dir: /home/developer
## It does mount
volumes:
  platformio-packages: